language: objective-c
osx_image: xcode7.2
env:
  global: 
    - FRAMEWORK_NAME=Express
before_install:
  - brew update
  - brew unlink carthage
  - brew install carthage
  - brew link carthage
  - brew tap crossroadlabs/tap
  - brew install libevhtp --without-oniguruma --with-shared
before_script:
  # bootstrap the dependencies for the project
  # you can remove if you don't have dependencies
  - carthage bootstrap --platform osx
before_deploy:
  - carthage build --no-skip-current
  - carthage archive $FRAMEWORK_NAME
  # - pod trunk push PathToRegex.podspec
script:
- xcodebuild build -project $FRAMEWORK_NAME.xcodeproj -scheme $FRAMEWORK_NAME
#- xcodebuild test -project Regex.xcodeproj -scheme Regex-iOS -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 6'
#- xcodebuild test -project Regex.xcodeproj -scheme Regex-tvOS -sdk appletvsimulator -destination 'platform=tvOS Simulator,name=Apple TV 1080p'
#- xcodebuild build -project Regex.xcodeproj -scheme Regex-watchOS -sdk watchsimulator -destination 'platform=watchOS Simulator,name=Apple Watch - 42mm'
notifications:
  email: false
deploy:
  provider: releases
  api_key:
  file: $FRAMEWORK_NAME.framework.zip
  skip_cleanup: true
  on:
    repo: crossroadlabs/$FRAMEWORK_NAME
    tags: true
